spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  # MongoDB 설정
  data:
    mongodb:
      host: ${MONGOHOST:localhost}
      port: ${MONGOPORT:27017}
      database: ${MONGODATABASE:myapp_logs}
      username: ${MONGOUSER:}
      password: ${MONGOPASSWORD:}
      authentication-database: admin