spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: buyit

logging:
  level:
    # Application 로깅
    com.willu.buyitornot: DEBUG
    # MongoDB 로깅
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: WARN