spring:
  profiles:
    active: live

  # MongoDB 설정
  mongodb:
    host: ${MONGOHOST}
    database: ${MONGODATABASE}
    port: ${MONGOPORT}
    username: ${MONGOUSER}
    password: ${MONGOPASSWORD}
    authentication-database: admin