spring:
  # MongoDB 설정
  data:
    mongodb:
      host: ${MONGOHOST}
      port: ${MONGOPORT}
      database: ${MONGODATABASE}
      username: ${MONGOUSER:}
      password: ${MONGOPASSWORD:}
      authentication-database: admin